### ISSUE TITLE
Suggestion: Place bins on sloped paths

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#10]
Thank you for fixing #4 !
It would be nice, if bins were placed on every second sloped path.

Now:
![grafik](https://user-images.githubusercontent.com/46271553/91883473-c600c980-ec84-11ea-805b-c8cb6ec3b8ac.png)

Suggestion:
![grafik](https://user-images.githubusercontent.com/46271553/91883519-d9139980-ec84-11ea-99d2-0f051b80bd66.png)

**Comment by tubbo** [comment]
why not just build bins on every sloped path?

**Comment by RundesBalli** [comment]
I don't know the english word for that.

In German we say "Gleichmäßigkeit" (uniformity), "Einheitlichkeit" (consistency).

But it would also be okay if bins are placed on every sloped path. :-)

**Comment by tubbo** [comment]
@RundesBalli I get what you're saying. Perhaps I could make a setting in the plugin that you can enable if you want bins placed on every sloped footpath, and if not enabled, it will just place bins on every other sloped footpath and ignore placing benches.

**Comment by RundesBalli** [comment]
That sounds great!
I am looking forward to the update :-)
