### ISSUE TITLE
"Ghost" Items Appear on Benches

### ISSUE THREAD

**Issue by tubbo** [tubbo/openrct2-benchwarmer#11]
Sometimes, I see benches and bins built by the plugin that look like this:

<img width="319" alt="Screen Shot 2020-09-01 at 1 53 25 PM" src="https://user-images.githubusercontent.com/113026/91888606-963ccc00-ec5a-11ea-80e7-b537086d69fd.png">

~~I haven't noticed this display having an effect on whether the peeps will use them. From what I've seen people just treat them like regular benches and bins, they just look odd.~~

**update:** They are not usable.

**Comment by RundesBalli** [comment]
I can reproduce this bug.

![grafik](https://user-images.githubusercontent.com/46271553/91892285-a6709d80-ec92-11ea-9a70-e85948ca9e7d.png)

At first I thought it was a texture error which is fixed after a restart of the game. But when I load the savegame, the same benches and bins are "ghosted". But the same b&b's are ghosted after a restart and reload.

If I reproduce this error in a scenario (in my case the "woodstock" scenario) and start the scenario new again, the ghosted textures will be seen in the same places. But I don't know why.

**Comment by RundesBalli** [comment]
@tubbo 
> I haven't noticed this display having an effect on whether the peeps will use them. From what I've seen people just treat them like regular benches and bins, they just look odd.

I used the `woodstock` scenario again and added 1000 visitors via the "cheat-module" from OpenRCT2. I set the energy of the visitors to the lowest and noticed, that the guests will not use any of the benches. I assume, that this behaviour is the same with the bins.

**Comment by RundesBalli** [comment]
I also noticed, that I can place a new bench over the ghosted one, but not over a correct one.


![cut](https://user-images.githubusercontent.com/46271553/91898642-53034d00-ec9c-11ea-9629-38a021785f70.gif)

**Comment by RundesBalli** [comment]
I don't know, if it is useful:

The problem occurs regardless of which benches or bins you use.

![video](https://user-images.githubusercontent.com/46271553/93367327-a359dd80-f84c-11ea-86cd-5f6bff66bc6c.gif)

**Comment by RundesBalli** [comment]
Works fine!

![grafik](https://user-images.githubusercontent.com/46271553/94324323-ad40b680-ff99-11ea-9c11-e93a743b6750.png)
