### ISSUE TITLE
Save placed benches/bins for the scenario

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#17]
It would be nice, if the plugin can remember which bench type and bin type was placed before and if the checkbox is ticked or not.

As an example:
You build 1000 paths, place banks and bins, and build another 1000 paths, but then you forget to select the banks and bins you have chosen before, then all existing banks and bins are overwritten with new ones.

![grafik](https://user-images.githubusercontent.com/46271553/93364908-6b9d6680-f849-11ea-83f9-265aba4426db.png)
The chosen bench is the third entry in the dropdown list, and the chosen bin is the second one.
When I add them and open the plugin again, it shows the first entrys of the list on both lists:
![grafik](https://user-images.githubusercontent.com/46271553/93365106-a99a8a80-f849-11ea-8b44-b043073c76bd.png)
Also the checkbox isn't checked anymore.

It would be nice, when the plugin could remember those settings at least for this session. If it is possible to save this settings in the savegame, it would be even better. But I don't know, if the savegame makes these plugin saves possible.

**Comment by tubbo** [comment]
If anyone is looking to contribute, this doesn't seem very difficult to do :)

**Comment by RundesBalli** [comment]
Unfortunately I don't know Javascript, otherwise I would have submitted a PR directly. :-D

It would be great if someone could program this. :-)
