### ISSUE TITLE
Cash can go into the red

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#18]
I don't know if this error is known or if it is intentional, but it is possible to place benches and bins without any cash money.

![grafik](https://user-images.githubusercontent.com/46271553/93365852-9b993980-f84a-11ea-9697-4c4e522bc0ef.png)
![grafik](https://user-images.githubusercontent.com/46271553/93365876-a3f17480-f84a-11ea-8b6e-e26ec98366a3.png)

I would suggest that if there is not enough cash money, the plugin throws an error message like this:
![grafik](https://user-images.githubusercontent.com/46271553/93366105-fb8fe000-f84a-11ea-92ff-2b41233e4440.png)
But with the text: `Insufficiend funds. Can not place benches and bins on all paths.` or something like that.

**Comment by tubbo** [comment]
I can do this but it won't be in German, unfortunately. At some point I'd like to add some kind of translation layer depending on the language you have selected, but that's a problem for future me to solve.

**Comment by tubbo** [comment]
Here's what it looks like: <img width="199" alt="Screen Shot 2020-09-23 at 7 41 01 PM" src="https://user-images.githubusercontent.com/113026/94084917-b7fe1e80-fdd4-11ea-89a9-9550d7502ab4.png">

**Comment by RundesBalli** [comment]
> I can do this but it won't be in German, unfortunately.
Of course it should be written in English. This was only an example based on a screenshot. And since I set my game to German, the example screenshot is also in German.

Thank you for the fix!

**Comment by tubbo** [comment]
released https://github.com/tubbo/openrct2-benchwarmer/releases/tag/v0.3.1

**Comment by RundesBalli** [comment]
Works! Thank you
