### ISSUE TITLE
Gets rid of existing things on path

### ISSUE THREAD

**Issue by Kodi4444** [tubbo/openrct2-benchwarmer#19]
it removes all light posts and jumping fountains and replaces existing benches and trash cans. witch waists money.
I would suggest an option to not overwrite existing items on paths.

**Comment by RundesBalli** [comment]
I would suggest, that the "do not overwrite" option is enabled by default.

**Comment by tubbo** [comment]
Thinking it would be better to just never re-build additions on footpaths that don't have a bench or bin. No option necessary, as you probably don't ever want this to happen...

**Comment by tubbo** [comment]
released https://github.com/tubbo/openrct2-benchwarmer/releases/tag/v0.3.1

**Comment by RundesBalli** [comment]
Works fine!
