### ISSUE TITLE
Include the investments in the financial overview.

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#20]
It would be nice, if the investments taken by the plugin are included in the "landscaping" row.
In German "landscaping" means "Landschaftsgestaltung" (fourth row)

Before:
![grafik](https://user-images.githubusercontent.com/46271553/93913610-9c781280-fd05-11ea-9e9f-4131ee5c81bd.png)

After:
![grafik](https://user-images.githubusercontent.com/46271553/93913643-a9950180-fd05-11ea-9fde-df6e982b5e77.png)
Nothing has changed except the amount of cash money.

If you place benches by hand, they are included in the landscape value:
![grafik](https://user-images.githubusercontent.com/46271553/93914392-c67e0480-fd06-11ea-9a92-6dd748e9313c.png)

**Comment by tubbo** [comment]
That would be nice. Not sure how that would be implemented though.   
  

  
  

  
  
>

**Comment by tubbo** [comment]
Hoping this will be fixed by #24.

**Comment by tubbo** [comment]
Confirmed that this will be fixed by #51

**Comment by tubbo** [comment]
I made a special build for this so we can test it on multiple machines:

[benchwarmer.js.zip](https://github.com/tubbo/openrct2-benchwarmer/files/8120840/benchwarmer.js.zip)

@RundesBalli if you could give this a shot at your convenience, just wanted to make sure it covered all the bases.

**Comment by RundesBalli** [comment]
![grafik](https://user-images.githubusercontent.com/46271553/155278739-0a0d4475-dcff-48cb-8edc-31796c3224ed.png)
![grafik](https://user-images.githubusercontent.com/46271553/155278762-8dab2469-bf29-4b8f-a516-725f1d32d79f.png)
Works fine! :-)
