### ISSUE TITLE
"Error Building Benches/Bins undefined not callable"

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#23]
![grafik](https://user-images.githubusercontent.com/46271553/94190999-29a99b80-fead-11ea-9c92-b2adc7ed67b3.png)

I've tested the new "insufficient funds" Feature (which works fine), and then added some money to test if it works again, if there is enough money.

Then this error message was displayed.

Side note: I don't think, that this has to do with the insufficient funds feature. Unfortunaly I've tested the insufficient funds feature, before I tested the plugin with enough money.

**Comment by RundesBalli** [comment]
I think I figured it out, what the cause of the problem is.

I have a completely empty park and have done the following tests:

1. No paths in the park and I click the `add` Button
=> nothing happens (as it should be, obviously). No additions, no error messages, nothing.

2. I create a path rectangle without anything and click `add`.
=> B&B are placed correctly.
This:
![grafik](https://user-images.githubusercontent.com/46271553/94264316-c7957880-ff36-11ea-8efb-f6aaeaa10214.png)
becomes this:
![grafik](https://user-images.githubusercontent.com/46271553/94264362-db40df00-ff36-11ea-999f-b548720f15f0.png)

3. Now I place one single bench on the path:
![grafik](https://user-images.githubusercontent.com/46271553/94264451-01667f00-ff37-11ea-863e-07c02134026c.png)
When I click `add`, the following error message appears:
![grafik](https://user-images.githubusercontent.com/46271553/94264479-13482200-ff37-11ea-9f42-931396c3c71c.png)
Even when I place the bench to the "correct" path, the error message appears:
![grafik](https://user-images.githubusercontent.com/46271553/94264562-34107780-ff37-11ea-8a56-e2f8f54d18e5.png)

4. I've tested it in prebuild scenarios. If one single bench or bin is placed anywhere inside the park, the plugin throws the earlier mentioned error message. If I remove the bench or bin, the plugin works properly.

**Comment by tubbo** [comment]
ahh I think I know what this is, I must have fat fingered the `includes` method :) it's supposed to detect whether the path already has a lamp addition and will not place bins/benches on it. will release a hotfix today at some point.

**Comment by RundesBalli** [comment]
Thank you! :)

**Comment by RundesBalli** [comment]
Works fine!
