### ISSUE TITLE
Additions are placed outside of the park

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#25]
Additions are placed outside of the park:

![grafik](https://user-images.githubusercontent.com/46271553/94325319-2fcb7500-ff9e-11ea-8363-3a21301459dc.png)

This scenario is the `Dusty Greens` park. Between the two park-areas, there are construction-rights. I assume it has something to do with @pencil|s fix in https://github.com/tubbo/openrct2-benchwarmer/commit/207c4a9fc79dc4f32fba0b1df0fdb55f28cac939

**Comment by tubbo** [comment]
That should be OK though, right? Because you have construction rights there?

I'm honestly not sure what the difference between "construction rights" and "I own this land" means...thought it just meant being able to build on the land vs. being able to manipulate the land.

**Comment by pencil** [comment]
Yeah, this is expected behavior if you have construction rights there.

**Comment by pencil** [comment]
On second thought: Maybe only elevated paths on land with construction rights should be considered?

**Comment by pencil** [comment]
I did some more digging: On land with construction rights, the player is only allowed to build underground or elevated – but not directly on the surface. The same logic applies to placing additions on paths. I addressed that in #26.

**Comment by RundesBalli** [comment]
> On second thought: Maybe only elevated paths on land with construction rights should be considered?

Thats what I mean. Thank you for the fix!
