### ISSUE TITLE
plugin file should be renamed for ease of recognition

### ISSUE THREAD

**Issue by Ryder17z** [tubbo/openrct2-benchwarmer#30]

**Comment by tubbo** [comment]
like, the actual filename? or the entire plugin? any suggestions?

**Comment by Ryder17z** [comment]
just the built .js file

**Comment by tubbo** [comment]
The plugin is named `benchwarmer.js`, I'm not sure I understand where the confusion lies...

**Comment by Ryder17z** [comment]
![image](https://user-images.githubusercontent.com/2000703/94720313-96f97880-0354-11eb-983b-1db72102793c.png)

**Comment by tubbo** [comment]
That's not the plugin, it's a script I use to help release the plugin. The plugin's build is available [on GitHub releases](https://github.com/tubbo/openrct2-benchwarmer/releases). That release script just changes the version in `package.json`, commits the change, creates a Git tag and pushes it to GitHub. From there, the [publish workflow](https://github.com/tubbo/openrct2-benchwarmer/blob/master/.github/workflows/publish.yml) takes over and basically does all the work. :)

**Comment by Ryder17z** [comment]
oh. my mistake.
