### ISSUE TITLE
Unable to use this plugin when the map does not use money

### ISSUE THREAD

**Issue by telk5093** [tubbo/openrct2-benchwarmer#31]
This plugin is great but it is unable to use it at infinite money map such as ``Icicle Worlds``.
Especially the map which has $0 when uncheck "No money" cheats.

**Comment by tubbo** [comment]
I don't have the means to test this on Icicle Worlds, but I tested it on Gravity Gardens just now and everything seems OK to me...the benches & bins built just fine. When you say "infinite money", you mean "no money", right? As in, no park entrance fees, no advertising, no profits...you just build stuff.

**Comment by telk5093** [comment]
Thanks for reply.
It was not my case but someone told me ask.

I meant there should be exception for the parks with infinite funds.
It seemd that there is a park with $0 cash with inifinite funds and a park with positive funds with infinite funds. ``Icicle Worlds`` is former.
You may check via cheats by enabling/disabling No Money cheat at Icicle Worlds.

I think there is no exception code for infinite funds, according to [here](https://github.com/tubbo/openrct2-benchwarmer/blob/master/src/add.js#L45).

**Comment by tubbo** [comment]
I don't understand how a park can have $0 cash and "infinite funds". Tried enabling and disabling No Money on Extreme Heights and I'm still able to build benches.

**Comment by telk5093** [comment]
I mean such situation like below:
![icicle worlds](https://user-images.githubusercontent.com/10726524/97023823-07309e00-1591-11eb-971c-d6f017318963.gif)

**Comment by tubbo** [comment]
ah i see, i guess some parks start out with $0. i was able to (sorta) reproduce the issue on extreme heights. it turns out that the plugin will still deduct money if any money exists, and in a "no money" scenario, your park still has a cash value. hopefully we can know when money has been turned off and then not deduct cash if the park has infinite money. thanks for the screenshots!

**Comment by tubbo** [comment]
@telk5093 can you try out this build and see if it works for you? https://github.com/tubbo/openrct2-benchwarmer/suites/1389973851/artifacts/22961199

**Comment by telk5093** [comment]
@tubbo Works fine 👍

**Comment by tubbo** [comment]
nice, i'll release 0.4.1 then :)
