### ISSUE TITLE
Suggestion: does not uploaded js file

### ISSUE THREAD

**Issue by AfxousaAjagara** [tubbo/openrct2-benchwarmer#34]
hello, actually I did not experienced any problem but I noticed that you did not upload 0.5.0 version of js file. is this on purposed or missing to upload file?

**Comment by dwaardenburg** [comment]
I would like it too if this would be done. I had to use the previous version now.

**Comment by Ryder17z** [comment]
the last entry in the changelog is:
 v0.4.1 (2020-10-23)

**Comment by lsippel1123** [comment]
Any idea if this will be fixed? I'm having trouble using the most recent version of this.

Or can someone direct me to an older version to use?

**Comment by kscheel** [comment]
@lsippel1123 You can see previous releases here: https://github.com/tubbo/openrct2-benchwarmer/releases

0.4.1 has the compiled .js file you need under "assets". Here is a direct link: https://github.com/tubbo/openrct2-benchwarmer/releases/download/v0.4.1/benchwarmer-v0.4.1.js

**Comment by josepharhar** [comment]
Here is a build of 0.5.0 which I created by running `npx yarn && npx yarn build` and copying the file from `build/benchwarmer.js`: [benchwarmer.zip](https://github.com/tubbo/openrct2-benchwarmer/files/6914265/benchwarmer.zip)

**Comment by tubbo** [comment]
Hey folks, sorry about that. I'll put the v0.5.0 up here on GitHub in a second. This version actually has no real changes between v0.4.1, I was just going through the motions of publishing the package to NPM so it could be used with another thing I'm working on, [RCTPM](https://github.com/tubbo/rctpm). Anyway, you're not missing out on anything as far as I know. :)

**Comment by tubbo** [comment]
OK it's all up there! v0.5.0's build is now available on https://github.com/tubbo/openrct2-benchwarmer/releases/tag/v0.5.0
