### ISSUE TITLE
Benches are built on sloped paths.

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#4]
Benches are built on sloped paths:

![grafik](https://user-images.githubusercontent.com/46271553/90982725-5181a880-e569-11ea-9884-06f738189817.png)

If you need more information, please let me know. I can recreate this bug on every map.

**Comment by RundesBalli** [comment]
@tubbo can you create a new Release?

**Comment by RundesBalli** [comment]
Works!

![grafik](https://user-images.githubusercontent.com/46271553/91882382-2d1d7e80-ec83-11ea-98d1-288cc5482b1c.png)

![grafik](https://user-images.githubusercontent.com/46271553/91882630-8be2f800-ec83-11ea-97d0-72ffaf25a774.png)

**Comment by tubbo** [comment]
@RundesBalli v0.2 is released, you got a shoutout :)

**Comment by RundesBalli** [comment]
Thank you! @tubbo :-)
