### ISSUE TITLE
Suggestion: Queue-TV

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#44]
As seen [here](https://www.reddit.com/r/rct/comments/ckmckq/do_we_tvs_in_the_queues_really_help/), queue-TV really work.

Maybe you can add an option to place queue-TV in every queue tile.

**Comment by tubbo** [comment]
Definitely makes sense to me.

**Comment by tubbo** [comment]
Released in https://github.com/tubbo/openrct2-benchwarmer/releases/tag/v0.5.1

**Comment by RundesBalli** [comment]
Thank you!
