### ISSUE TITLE
Cannot run utility with "Preserve other additions" checked

### ISSUE THREAD

**Issue by DDoop** [tubbo/openrct2-benchwarmer#47]
When I have this option enabled, I get an in-game error message reading "Error Building Benches/Bins undefined not callable (property 'includes' of [object Array])." When I turn this off, it works fine. This happens any time there are path decorations of any kind in my park. Disabling the preserve additions option fixes the problem.

I don't personally actually want non-functional path decorations, but I didn't see this bug reported so I figured I would.

Using OpenRCT2 v0.3.4.1 on Windows, plugin v0.5.0

**Comment by tubbo** [comment]
This seems to work now as of https://github.com/tubbo/openrct2-benchwarmer/releases/tag/v0.5.1
