### ISSUE TITLE
"Add benches and bins as paths are placed" doesn't respect options

### ISSUE THREAD

**Issue by PhasecoreX** [tubbo/openrct2-benchwarmer#53]
Seems like the plugin attempts to put bins/benches on queue line paths that are placed (instead of the queue line TVs), as well as it puts bins on all the sloped paths even if "Build bins on all sloped footpaths" is disabled.

Also, would it be possible to disable queue line additions altogether? Maybe a "None" option in the dropdown. I want automatic benches and bins, but I'll manually add queue line TVs if I need them.

**Comment by tubbo** [comment]
@PhasecoreX Have you tried changing one of the options in the plugin and then seeing if it "takes"? I've noticed that default settings don't seem to be respected. If I want to build benches/bins as I place footpaths, I have to open the plugin window first before that begins taking effect, rather than just automatically all the time.

**Comment by PhasecoreX** [comment]
Yes, I've switched the options on and off before, and I see my modified settings in the `plugin.store.json` file. I think your issue with it not doing the auto placement until you open the plugin window is because you have your `context.subscribe("action.execute")` inside of the `ui.registerMenuItem(name, () => {})`. Move it out so it's just inside `function main() {}` and you should be good.

The bins/benches will build as I place path, it's just that when I place queue lines it'll show the error "Can't position this here... Cannot place these on queue line area". That's because it's trying to place a bin/bench on the queue line:

https://github.com/tubbo/openrct2-benchwarmer/blob/2fe8a8d00a5aa262fca373924882d0b13efcf53a/src/index.ts#L81-L83

This doesn't take into account queue line TVs, only the chosen bin and bench. It also ignores "Build bins on all sloped footpaths" option completely: if the path is sloped, it will always choose to place the bin.
