### ISSUE TITLE
Suggestion: Ability to auto-run

### ISSUE THREAD

**Issue by csm10495** [tubbo/openrct2-benchwarmer#54]
It would be amazing if either this could auto run either when the path window is closed or on some sort of interval: (like once a day or month, etc). 

Thanks!

**Comment by RundesBalli** [comment]
You have to initialize the settings on game start:
![grafik](https://user-images.githubusercontent.com/46271553/160210116-31a3233e-5e9c-4497-b6f8-8a05e278a3bb.png)

**Comment by csm10495** [comment]
What version is that? I don't see that option in 0.5.1: 
![image](https://user-images.githubusercontent.com/5749838/160211500-b910853b-8e62-4cc2-990f-4ca03108b829.png)

**Comment by RundesBalli** [comment]
Nevermind. Its not released yet.

Use this: https://github.com/tubbo/openrct2-benchwarmer/issues/14#issuecomment-1049046612
:-)

**Comment by csm10495** [comment]
That feature is cool, but if you build designs that have paths already included they don't get benches, etc. automatically.

**Comment by RundesBalli** [comment]
> That feature is cool, but if you build designs that have paths already included they don't get benches, etc. automatically.

As I mentioned here: https://github.com/tubbo/openrct2-benchwarmer/issues/14#issuecomment-1050585967

Please read the full issue / suggestion.

**Comment by tubbo** [comment]
@csm10495 You can use the bench brush from [scenery manager](https://github.com/Sadret/openrct2-scenery-manager#Bench-Brush) for this particular use case, placing benches and bins in a particular area. It's also useful for maintaining different kinds of footpath additions in different areas of your park, such as the stone bench for an egyptian-themed land or the space bench for a futuristic land. As the new `.park` save format has landed, you probably won't want to use this plugin for large-scale parks that are heavily themed. This plugin has always been primarily intended as a utility for scenario play, making it easier to keep your park tidy (and thus, your park rating up) and win scenarios.

**Comment by tubbo** [comment]
Gonna close this since we don't have any way of knowing when you plop down a prebuilt ride that has paths in it, so there's no way to do that in this plugin, and placing benches/bins in a given area is covered by scenery manager.
