### ISSUE TITLE
Pre-release bug: Queue lines

### ISSUE THREAD

**Issue by csm10495** [tubbo/openrct2-benchwarmer#55]
I have queue line tvs enabled and auto place on.

See video

https://user-images.githubusercontent.com/5749838/160219230-6ce20e33-d77b-4996-90ca-08bfe7626e0e.mp4

:

**Comment by RundesBalli** [comment]
As I mentioned here: https://github.com/tubbo/openrct2-benchwarmer/issues/14#issuecomment-1050213357

**Comment by tubbo** [comment]
This unfortunately broke type checks so I'm looking into a more maintainable solution currently.
