### ISSUE TITLE
Doesn't recognize custom benches/bins

### ISSUE THREAD

**Issue by cruzy80** [tubbo/openrct2-benchwarmer#57]
Only seems to pull default bins/benches from RCT2. Won't recognize any custom benches or bins.

**Comment by tubbo** [comment]
@cruzy80 When you say "custom" what do you mean? Like stuff you've downloaded?

They _might_ not actually be registering as benches or bins. We are querying OpenRCT2 for all of the `footpath_addition` object types that are loaded into the game [right here](https://github.com/tubbo/openrct2-benchwarmer/blob/master/src/index.ts#L10-L11), which is how we populate the dropdowns and allow you to choose a bench and bin.

Can you make sure that guests are e.g. sitting on your custom bench and throwing trash in your custom bin? If not, they may just be scenery additions and not actually functional.

**Comment by cruzy80** [comment]
Hi, they are custom benches that can be sat on.  Is it where they are
saved? My custom bench scenery is saved under the Open RCT Object Directory
while the default scenery is under the Steam RCT2 directory. Also the
benches that Benchwarmer does recognize has the extension .json, while
everything custom I;ve downloaded is .dat  also I've tried copying the
bench .dats to the Steam RCT2 folder, but it doesn't work.
,
[image: image.png]
[image: image.png]

**Comment by tubbo** [comment]
@cruzy80 Whatever images you sent did not come through, unfortunately. The benches/bins that Benchwarmer is using come from [this line of code](https://github.com/tubbo/openrct2-benchwarmer/blob/master/src/index.ts#L10), which calls into OpenRCT2 to see what objects we have available. If your scenery isn't making it into that list, the game itself is not recognizing it as a "footpath addition", so we won't be able to know it's there.
