### ISSUE TITLE
Cannot place these on queue line area

### ISSUE THREAD

**Issue by jarrndewitt** [tubbo/openrct2-benchwarmer#65]
I installed the plugin (v1.0.1) in OpenRCT2 v 0.4.1, opened the configuration window, chose a bench, a bin, a queue TV (doesn't matter which ones) and checked "Add benches and bins as paths are placed" (other checkboxes don't matter as well).

Whenever I place a queue line now, a red window pops open: "Can't position this here... Cannot place these on queue line area" as if the plugin was trying to place a bin or bench on the just built queue line. However, there is no queue TV build as I would expect.

When I hit "build on all paths", queue TVs are build as expected.

**Comment by tubbo** [comment]
It's trying to build paths on places that it can't, I think.

**Comment by tubbo** [comment]
@jarrndewitt we already have an open issue for this: https://github.com/tubbo/openrct2-benchwarmer/issues/55, please check the issue list before creating new ones.
