### ISSUE TITLE
No more bins are placed and there are lanterns in the queue lines

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#76]
Probably something has been changed in the game, that the API for the addon has changed, or something?

In any case, it is no longer possible to place bins. Queue TV is only placed on every second path, and there are lanterns on the others. In the meantime, benches are also no longer placed.

Lanterns:
![grafik](https://github.com/tubbo/openrct2-benchwarmer/assets/46271553/40bef9cc-746b-4a3f-9803-ed64628beb40)

No more bins:
![grafik](https://github.com/tubbo/openrct2-benchwarmer/assets/46271553/016ed214-5ad3-44cd-9d6d-589292b1ed9a)

The error message is "cannot place that here, can not be placed in queue":
![grafik](https://github.com/tubbo/openrct2-benchwarmer/assets/46271553/d2c6d8fd-6e4f-4949-a4a6-eb1e85a82628)

**Comment by KyuuGryphon** [comment]
Haven't been having this issue with lanterns, but I've definitely been having issues with bins. The plugin just doesn't place them at all, either automatically or using the Build on All Paths option. Version 0.5.1's Add button works, but 1.0.0 and 1.0.1 do not.

**Comment by Soma91** [comment]
This [PR](https://github.com/OpenRCT2/OpenRCT2/pull/20177) changed the way the indices of `footpathadditionplace` work. If you replace `addition + 1` with just `addition` in the Plugin js file it works as expected again.

**Comment by KyuuGryphon** [comment]
> This [PR](https://github.com/OpenRCT2/OpenRCT2/pull/20177) changed the way the indices of `footpathadditionplace` work. If you replace `addition + 1` with just `addition` in the Plugin js file it works as expected again.

Can confirm, that does the trick here! Much appreciated, thank you. :)

**Comment by JensMakerAdventures** [comment]
> This [PR](https://github.com/OpenRCT2/OpenRCT2/pull/20177) changed the way the indices of `footpathadditionplace` work. If you replace `addition + 1` with just `addition` in the Plugin js file it works as expected again.

Yes, this works. You need to do it in 2 places in the code and everything is OK again :)

**Comment by jayjayseal** [comment]
Can confirm this works. Thank you for finding this.

**Comment by RundesBalli** [comment]
Can confirm this https://github.com/tubbo/openrct2-benchwarmer/issues/76#issuecomment-1793735455
