### ISSUE TITLE
Laterns & Placing problems still occur in version 1.1.0

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#85]
These errors still occur in the newly released v. 1.1.0.

https://github.com/tubbo/openrct2-benchwarmer/pull/82
https://github.com/tubbo/openrct2-benchwarmer/issues/55
https://github.com/tubbo/openrct2-benchwarmer/issues/14#issuecomment-1050213357

**Comment by tubbo** [comment]
None of these issues were meant to be fixed by v1.1.0, I was just making sure the release system worked before getting those bugs fixed. The PR you posted is still open and I haven't had a chance to test it yet.

**Comment by RundesBalli** [comment]
Ok
