### ISSUE TITLE
Benches and Bins are only placed on the lowest level

### ISSUE THREAD

**Issue by RundesBalli** [tubbo/openrct2-benchwarmer#9]
When you build paths in different levels, then only the lowest level gets Benches and Bins.

![grafik](https://user-images.githubusercontent.com/46271553/91883007-175c8900-ec84-11ea-8aff-afe50b2c87f0.png)

![grafik](https://user-images.githubusercontent.com/46271553/91883076-31966700-ec84-11ea-9386-eb2b959b1b20.png)

![grafik](https://user-images.githubusercontent.com/46271553/91883213-69051380-ec84-11ea-86d6-2a81f6247b98.png)

**Comment by tubbo** [comment]
ahh _that_ is why sometimes paths don't get stuff built on them. thanks for figuring this out.

**Comment by RundesBalli** [comment]
You're welcome :-)
