### ISSUE TITLE
can't position this here... unknown type when using default benches and bins

### ISSUE THREAD

**Issue by RunninPigeon** [tubbo/openrct2-benchwarmer#96]
![Screenshot 2024-04-08 124627](https://github.com/tubbo/openrct2-benchwarmer/assets/68831086/2ff3880e-0176-432a-9c90-ef90d3d92e28)

**Comment by tubbo** [comment]
just tried this in the (newly-released) v1.1.1 and didn't get the error.

**Comment by tubbo** [comment]
@RunninPigeon let me know if this is still happening for you in the latest version and i'll re-open
